"""
Daily Report model — employee end-of-day work summaries.

WHY THIS EXISTS: Employees submit daily reports describing what they worked on,
accomplishments, blockers, and plans. Reports can be written manually or auto-generated
by the AI assistant. The is_ai_generated flag helps managers distinguish between
AI-drafted and human-written content.

STATUS LIFECYCLE:
  draft     = Employee is still writing. Not visible to managers in summary views.
  submitted = Finalized. Visible on manager dashboards and included in analytics.
  
  The status field is NOT auto-advanced. The employee explicitly submits. This gives
  them control over when their report is "published" versus still being edited.

FIELD DESIGN NOTES:
  - content (Text, not String): Daily reports can be lengthy (paragraphs of notes).
    Text type supports unlimited length in both SQLite and PostgreSQL.
  - date (Date): The calendar date this report covers. Separate from created_at because
    an employee might create today's report tomorrow morning (e.g., end-of-day report
    written next day). The date field anchors the report to the correct work day.
  - is_ai_generated (Boolean): Set to True when the report was generated via
    the AI assistant endpoint. This is informational, not functional — AI-generated
    reports can be edited after generation (the flag doesn't change).

RELATIONSHIP CASCADE:
  Follows User model's cascade pattern. Deleting a user removes their reports.
"""

import enum
import uuid
from datetime import date, datetime, timezone

from sqlalchemy import Boolean, Date, DateTime, Enum, ForeignKey, Text
from sqlalchemy import Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class ReportStatus(str, enum.Enum):
    draft = "draft"
    submitted = "submitted"


class DailyReport(Base):
    __tablename__ = "daily_reports"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(), ForeignKey("users.id"), nullable=False
    )
    # Full report content. Text type supports arbitrarily long entries.
    content: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[ReportStatus] = mapped_column(
        Enum(ReportStatus), default=ReportStatus.draft, nullable=False
    )
    # The work date this report refers to (not the submission date).
    date: Mapped[date] = mapped_column(Date, nullable=False)
    # True if the initial content was generated by the AI assistant.
    # The user may have edited it afterwards — this flag only tracks origin.
    is_ai_generated: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    user = relationship("User", back_populates="reports")
